workers: 64

world_size: 1
rank: 0
dist_url: tcp://localhost:40000
dist_backend: nccl
port: 40000
node: localhost

distributed: True
seed:
gpu:
ngpu: 8
mem_gb: 64
pin_mem: True

slurm: True
slurm_suffix: ""
slurm_partition: research
slurm_timeout: 360
nodelist: ""
exclude: ""
